# Rrf https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37
instance_class: F1

env_variables:
  REDIS_HOST: 10.200.0.4
  REDIS_PORT: "6379"

vpc_access_connector:
  name: projects/syl-phonebook/locations/southamerica-east1/connectors/appengine-vpc-access
  # Send all egress traffic through the VPC Access Connector
  egress_setting: all-traffic 

# Mode detail in https://cloud.google.com/appengine/docs/standard/python3/configuring-warmup-requests
inbound_services:
- warmup

automatic_scaling:
  min_instances: 1
  max_instances: 10
